import { Injectable, Logger } from '@nestjs/common';
import * as fs from 'fs/promises';
import { existsSync, readdirSync } from 'fs';
import * as path from 'path';
import { ConfigService } from '../config/config.service';
import { ContextDocumentService } from './context-document.service';
import { BRIEFING_OUTPUT_DIR } from './briefing.types';

/**
 * Parsed briefing data extracted from a briefing markdown file.
 */
export interface ParsedBriefing {
  /** Task title from the briefing header */
  title: string;
  /** Mode at the time the briefing was created */
  mode: string;
  /** Key decisions from the briefing */
  decisions: string[];
  /** Pending tasks from the briefing */
  pendingTasks: string[];
  /** Changed files listed in the briefing */
  changedFiles: string[];
  /** Suggested command to resume work */
  resumeCommand: string;
}

/**
 * Result of restoring context from a briefing.
 */
export interface RestoreResult extends ParsedBriefing {
  /** Whether context.md was successfully restored */
  contextRestored: boolean;
  /** Path to the briefing file that was loaded */
  briefingPath: string;
}

/**
 * Service for loading and parsing briefing documents to restore session context.
 *
 * Reads briefing markdown files generated by BriefingService and restores
 * the session context (context.md) so work can be resumed in a new session.
 */
@Injectable()
export class BriefingLoaderService {
  private readonly logger = new Logger(BriefingLoaderService.name);

  constructor(
    private readonly configService: ConfigService,
    private readonly contextDocumentService: ContextDocumentService,
  ) {}

  /**
   * Find the most recent briefing file in the briefings directory.
   * Files are sorted lexicographically (ISO timestamp names sort chronologically).
   *
   * @returns Absolute path to the most recent briefing, or null if none found
   */
  findMostRecentBriefing(): string | null {
    const projectRoot = this.configService.getProjectRoot();
    const briefingDir = path.join(projectRoot, BRIEFING_OUTPUT_DIR);

    if (!existsSync(briefingDir)) {
      this.logger.debug(`Briefings directory does not exist: ${briefingDir}`);
      return null;
    }

    const files = readdirSync(briefingDir)
      .filter(f => f.endsWith('.md'))
      .sort();

    if (files.length === 0) {
      this.logger.debug('No briefing files found');
      return null;
    }

    // Last file is the most recent (ISO timestamps sort chronologically)
    return path.join(briefingDir, files[files.length - 1]);
  }

  /**
   * Parse a briefing markdown string into structured data.
   * Pure function - no side effects.
   *
   * @param content - Raw markdown content of a briefing file
   * @returns Parsed briefing data
   */
  parseBriefingMarkdown(content: string): ParsedBriefing {
    const result: ParsedBriefing = {
      title: 'Untitled',
      mode: 'PLAN',
      decisions: [],
      pendingTasks: [],
      changedFiles: [],
      resumeCommand: '',
    };

    if (!content.trim()) {
      return result;
    }

    // Extract title: "# Briefing: <title>"
    const titleMatch = content.match(/^# Briefing: (.+)$/m);
    if (titleMatch) {
      result.title = titleMatch[1].trim();
    }

    // Extract mode: "**Mode**: <mode>"
    const modeMatch = content.match(/\*\*Mode\*\*: (\w+)/);
    if (modeMatch) {
      result.mode = modeMatch[1];
    }

    // Extract list items from sections
    result.decisions = this.extractSectionItems(content, 'Decisions');
    result.changedFiles = this.extractSectionItems(content, 'Changed Files');
    result.pendingTasks = this.extractSectionItems(content, 'Pending Tasks');

    // Extract resume command from code block
    const resumeMatch = content.match(/## Resume Command\s*\n```\n([\s\S]*?)\n```/);
    if (resumeMatch) {
      result.resumeCommand = resumeMatch[1].trim();
    }

    return result;
  }

  /**
   * Load a briefing file and parse it.
   *
   * @param briefingPath - Optional path to a specific briefing file.
   *                       If omitted, loads the most recent briefing.
   * @returns Parsed briefing data
   * @throws Error if no briefing files exist or file not found
   */
  async loadBriefing(briefingPath?: string): Promise<ParsedBriefing & { briefingPath: string }> {
    let resolvedPath: string;

    if (briefingPath) {
      if (!existsSync(briefingPath)) {
        throw new Error(`Briefing file not found: ${briefingPath}`);
      }
      resolvedPath = briefingPath;
    } else {
      const mostRecent = this.findMostRecentBriefing();
      if (!mostRecent) {
        throw new Error(
          'No briefing files found in docs/codingbuddy/briefings/. Create one first with create_briefing.',
        );
      }
      resolvedPath = mostRecent;
    }

    const content = await fs.readFile(resolvedPath, 'utf-8');
    const parsed = this.parseBriefingMarkdown(content);

    this.logger.log(`Loaded briefing: ${resolvedPath}`);

    return { ...parsed, briefingPath: resolvedPath };
  }

  /**
   * Load a briefing and restore session context (context.md).
   *
   * 1. Load and parse the briefing file
   * 2. Call resetContext to restore context.md with briefing data
   * 3. Return summary for the AI to display
   *
   * @param briefingPath - Optional path to a specific briefing file
   * @returns Restore result with summary
   */
  async restoreContext(briefingPath?: string): Promise<RestoreResult> {
    const briefing = await this.loadBriefing(briefingPath);

    // Restore context.md using resetContext (PLAN mode reset)
    await this.contextDocumentService.resetContext({
      title: briefing.title,
      task: `Resumed from briefing: ${briefing.resumeCommand}`,
      decisions: briefing.decisions,
      notes: briefing.pendingTasks,
    });

    this.logger.log(`Context restored from briefing: ${briefing.briefingPath}`);

    return {
      ...briefing,
      contextRestored: true,
    };
  }

  /**
   * Extract list items (lines starting with "- ") from a named section.
   * Filters out placeholder text (lines starting with "_").
   *
   * @param content - Full markdown content
   * @param sectionName - Section header name (e.g., "Decisions")
   * @returns Array of extracted items
   */
  private extractSectionItems(content: string, sectionName: string): string[] {
    // Match from section header to next section header or end
    const sectionRegex = new RegExp(`## ${sectionName}\\s*\\n([\\s\\S]*?)(?=\\n## |$)`);
    const sectionMatch = content.match(sectionRegex);

    if (!sectionMatch) {
      return [];
    }

    return sectionMatch[1]
      .split('\n')
      .filter(line => line.startsWith('- '))
      .map(line => line.slice(2).trim());
  }
}
