#!/usr/bin/env npx ts-node
/**
 * Wiki Generator — produces architecture map, API inventory,
 * and decision log under docs/codingbuddy/wiki/.
 *
 * Usage: npx ts-node scripts/wiki/generate-wiki.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import {
  parseImports,
  parseToolDefinitions,
  parseContextDecisions,
  buildModuleDependencyMap,
  type ToolInfo,
  type DecisionEntry,
} from './parsers';

const ROOT = path.resolve(__dirname, '../..');
const SRC_DIR = path.join(ROOT, 'apps/mcp-server/src');
const HANDLERS_DIR = path.join(SRC_DIR, 'mcp/handlers');
const WIKI_DIR = path.join(ROOT, 'docs/codingbuddy/wiki');
const CONTEXT_PATH = path.join(ROOT, 'docs/codingbuddy/context.md');

// ---------------------------------------------------------------------------
// File utilities
// ---------------------------------------------------------------------------

function walkTs(dir: string, base: string = dir): string[] {
  const files: string[] = [];
  if (!fs.existsSync(dir)) return files;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory() && entry.name !== 'node_modules' && entry.name !== '__tests__') {
      files.push(...walkTs(full, base));
    } else if (entry.isFile() && /\.tsx?$/.test(entry.name) && !entry.name.endsWith('.spec.ts')) {
      files.push(path.relative(base, full));
    }
  }
  return files;
}

// ---------------------------------------------------------------------------
// Architecture map
// ---------------------------------------------------------------------------

function generateArchitecture(): string {
  const tsFiles = walkTs(SRC_DIR);
  const fileImports: Record<string, string[]> = {};

  for (const file of tsFiles) {
    const source = fs.readFileSync(path.join(SRC_DIR, file), 'utf-8');
    const imports = parseImports(source);
    if (imports.length > 0) {
      fileImports[file] = imports;
    }
  }

  const depMap = buildModuleDependencyMap(fileImports);

  // Collect all modules
  const allModules = new Set<string>();
  for (const [mod, deps] of Object.entries(depMap)) {
    allModules.add(mod);
    for (const d of deps) allModules.add(d);
  }

  const lines: string[] = [
    '# Architecture Map',
    '',
    '> Auto-generated by `yarn wiki:generate`. Do not edit manually.',
    '',
    '## Module Dependency Graph',
    '',
    '```',
  ];

  // Sort modules for deterministic output
  const sortedModules = [...allModules].sort();
  for (const mod of sortedModules) {
    const deps = depMap[mod];
    if (deps && deps.length > 0) {
      lines.push(`${mod} → ${deps.join(', ')}`);
    }
  }
  lines.push('```', '');

  // Module descriptions
  lines.push('## Modules', '');
  const moduleDescriptions: Record<string, string> = {
    mcp: 'MCP protocol handlers — tool dispatch via Chain of Responsibility',
    rules: 'Rules file reading, agent/skill schema validation',
    agent: 'Agent service and prompt building',
    keyword: 'PLAN/ACT/EVAL/AUTO mode detection and auto-execution',
    checklist: 'Checklist generation service',
    context: 'Context document persistence (docs/codingbuddy/context.md)',
    analyzer: 'Project analysis — conventions, code sampling, package analysis',
    config: 'Project configuration loading and diff detection',
    skill: 'Skill recommendation and trigger matching',
    state: 'State persistence for modes (autopilot, ralph, etc.)',
    model: 'Model resolution and constants',
    tui: 'React/Ink terminal UI dashboard',
    shared: 'Common utilities (async, error, format, path, file, security, version)',
    diagnostic: 'Diagnostic logging',
    cli: 'CLI entry point and TUI launcher',
    custom: 'Custom project-specific extensions',
  };

  for (const mod of sortedModules) {
    const desc = moduleDescriptions[mod] ?? '';
    const deps = depMap[mod];
    lines.push(`### ${mod}`);
    if (desc) lines.push(`${desc}`);
    if (deps && deps.length > 0) {
      lines.push(`- **Dependencies:** ${deps.join(', ')}`);
    }
    lines.push('');
  }

  // File count per module
  lines.push('## File Distribution', '');
  lines.push('| Module | Files |');
  lines.push('|--------|-------|');
  const moduleCounts: Record<string, number> = {};
  for (const file of tsFiles) {
    if (!file.includes('/')) continue; // skip root-level files
    const mod = file.split('/')[0];
    moduleCounts[mod] = (moduleCounts[mod] ?? 0) + 1;
  }
  for (const mod of Object.keys(moduleCounts).sort()) {
    lines.push(`| ${mod} | ${moduleCounts[mod]} |`);
  }
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// API Inventory
// ---------------------------------------------------------------------------

function generateApiInventory(): string {
  const lines: string[] = [
    '# API Inventory',
    '',
    '> Auto-generated by `yarn wiki:generate`. Do not edit manually.',
    '',
  ];

  // --- Tools ---
  lines.push('## Tools', '');
  lines.push('| Tool | Description | Handler |');
  lines.push('|------|-------------|---------|');

  if (fs.existsSync(HANDLERS_DIR)) {
    const handlerFiles = fs.readdirSync(HANDLERS_DIR)
      .filter(f => f.endsWith('.handler.ts') && f !== 'base.handler.ts' && f !== 'abstract-handler.ts');

    const allTools: Array<ToolInfo & { handler: string }> = [];

    for (const file of handlerFiles.sort()) {
      const source = fs.readFileSync(path.join(HANDLERS_DIR, file), 'utf-8');
      const tools = parseToolDefinitions(source);
      const handlerName = file.replace('.handler.ts', '');
      for (const tool of tools) {
        allTools.push({ ...tool, handler: handlerName });
      }
    }

    for (const tool of allTools) {
      lines.push(`| \`${tool.name}\` | ${tool.description} | ${tool.handler} |`);
    }
  }

  // Also check for parallel-validation handler
  const pvHandlerPath = path.join(SRC_DIR, 'parallel-validation/parallel-validation.handler.ts');
  if (fs.existsSync(pvHandlerPath)) {
    const source = fs.readFileSync(pvHandlerPath, 'utf-8');
    const tools = parseToolDefinitions(source);
    for (const tool of tools) {
      lines.push(`| \`${tool.name}\` | ${tool.description} | parallel-validation |`);
    }
  }

  lines.push('');

  // --- Resources ---
  lines.push('## Resources', '');
  lines.push('| URI | Name | Description |');
  lines.push('|-----|------|-------------|');
  lines.push('| `config://project` | Project Configuration | Project-specific configuration including tech stack, architecture, and conventions |');
  lines.push('| `rules://rules/core.md` | Core Rules | Core workflow rules (modes, error recovery) |');
  lines.push('| `rules://rules/project.md` | Project Setup | Project structure and tech stack template |');
  lines.push('| `rules://rules/augmented-coding.md` | Augmented Coding | TDD cycle, code quality principles |');
  lines.push('| `rules://agents/{name}.json` | Agent Definitions | Agent profiles (dynamically listed) |');
  lines.push('');

  // --- Prompts ---
  lines.push('## Prompts', '');
  lines.push('| Prompt | Description | Arguments |');
  lines.push('|--------|-------------|-----------|');
  lines.push('| `activate_agent` | Activate a specific specialist agent with project context | `role` (required) — Role name (e.g. frontend-developer) |');
  lines.push('');

  // --- Summary ---
  lines.push('## Summary', '');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Decision Log
// ---------------------------------------------------------------------------

function generateDecisionLog(): string {
  const lines: string[] = [
    '# Decision Log',
    '',
    '> Auto-generated by `yarn wiki:generate`. Do not edit manually.',
    '',
  ];

  if (fs.existsSync(CONTEXT_PATH)) {
    const content = fs.readFileSync(CONTEXT_PATH, 'utf-8');
    const decisions = parseContextDecisions(content);

    if (decisions.length > 0) {
      lines.push('| Mode | Timestamp | Decision |');
      lines.push('|------|-----------|----------|');
      for (const d of decisions) {
        lines.push(`| ${d.mode} | ${d.timestamp} | ${d.decision} |`);
      }
    } else {
      lines.push('No decisions recorded yet.');
    }
  } else {
    lines.push('No context document found at `docs/codingbuddy/context.md`.');
  }

  lines.push('');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  fs.mkdirSync(WIKI_DIR, { recursive: true });

  const architecture = generateArchitecture();
  const apiInventory = generateApiInventory();
  const decisionLog = generateDecisionLog();

  fs.writeFileSync(path.join(WIKI_DIR, 'architecture.md'), architecture);
  fs.writeFileSync(path.join(WIKI_DIR, 'api-inventory.md'), apiInventory);
  fs.writeFileSync(path.join(WIKI_DIR, 'decision-log.md'), decisionLog);

  console.log('Wiki generated successfully:');
  console.log(`  - ${path.relative(ROOT, path.join(WIKI_DIR, 'architecture.md'))}`);
  console.log(`  - ${path.relative(ROOT, path.join(WIKI_DIR, 'api-inventory.md'))}`);
  console.log(`  - ${path.relative(ROOT, path.join(WIKI_DIR, 'decision-log.md'))}`);
}

main();
