import { readFile, writeFile } from 'fs/promises';
import { existsSync, mkdirSync } from 'fs';
import { dirname } from 'path';

export interface RuleStats {
  count: number;
  lastUsed: number;
  /**
   * True when the rule was generated by the self-evolving pipeline
   * (#1444). Used to separate auto-generated rules from manual rules in
   * effectiveness reports.
   */
  generatedRule?: boolean;
  /**
   * Baseline failure rate captured when a generated rule was first
   * introduced. Combined with {@link currentFailureRate} to compute
   * effectiveness reduction percent.
   */
  baselineFailureRate?: number;
  /**
   * Latest observed failure rate for a generated rule.
   */
  currentFailureRate?: number;
}

export interface RuleEffectivenessReport {
  totalRulesTracked: number;
  generatedAt: number;
  entries: Array<{
    name: string;
    count: number;
    lastUsed: number;
  }>;
}

export class RuleTracker {
  private stats: Record<string, RuleStats> = {};

  constructor(private readonly statsPath: string) {}

  static async fromFile(statsPath: string): Promise<RuleTracker> {
    const tracker = new RuleTracker(statsPath);
    try {
      const raw = await readFile(statsPath, 'utf-8');
      tracker.stats = JSON.parse(raw);
    } catch {
      // File doesn't exist or is invalid — start fresh
    }
    return tracker;
  }

  trackRuleUsage(ruleNames: string[]): void {
    const now = Date.now();
    for (const name of ruleNames) {
      if (!name) continue;
      if (this.stats[name]) {
        this.stats[name].count += 1;
        this.stats[name].lastUsed = now;
      } else {
        this.stats[name] = { count: 1, lastUsed: now };
      }
    }
  }

  /**
   * Mark a rule as auto-generated by the self-evolving pipeline (#1444).
   * Creates the stat entry if the rule has never been tracked.
   */
  markRuleAsGenerated(ruleName: string): void {
    if (!ruleName) return;
    if (!this.stats[ruleName]) {
      this.stats[ruleName] = { count: 0, lastUsed: Date.now() };
    }
    this.stats[ruleName].generatedRule = true;
  }

  /**
   * Record a baseline or current failure rate for a generated rule
   * (#1444). Baseline is captured once when the rule is introduced;
   * current is updated as new execution data arrives.
   *
   * A rule must be marked as generated (see {@link markRuleAsGenerated})
   * before failure rates are recorded — otherwise the call is a no-op.
   */
  recordFailureRate(ruleName: string, rate: number, kind: 'baseline' | 'current'): void {
    if (!ruleName) return;
    const stat = this.stats[ruleName];
    if (!stat || !stat.generatedRule) return;
    if (kind === 'baseline') {
      stat.baselineFailureRate = rate;
    } else {
      stat.currentFailureRate = rate;
    }
  }

  getStats(): Record<string, RuleStats> {
    return JSON.parse(JSON.stringify(this.stats));
  }

  detectUnusedRules(allRuleNames: string[], thresholdDays: number): string[] {
    const thresholdMs = thresholdDays * 24 * 60 * 60 * 1000;
    const now = Date.now();
    const unused: string[] = [];

    for (const name of allRuleNames) {
      const stat = this.stats[name];
      if (!stat || now - stat.lastUsed > thresholdMs) {
        unused.push(name);
      }
    }

    return unused;
  }

  generateReport(): RuleEffectivenessReport {
    const entries = Object.entries(this.stats)
      .map(([name, stat]) => ({
        name,
        count: stat.count,
        lastUsed: stat.lastUsed,
      }))
      .sort((a, b) => b.count - a.count);

    return {
      totalRulesTracked: entries.length,
      generatedAt: Date.now(),
      entries,
    };
  }

  async save(): Promise<void> {
    const dir = dirname(this.statsPath);
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
    await writeFile(this.statsPath, JSON.stringify(this.stats, null, 2), 'utf-8');
  }
}
